# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junto_api', '0002_auto_20171005_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(related_name='dishes', related_query_name='dish', to='junto_api.Category', verbose_name='Категории'),
        ),
    ]
