# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junto_api', '0003_auto_20171005_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', related_query_name='subcategory', to='junto_api.Category'),
        ),
    ]
