# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junto_api', '0004_auto_20171005_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, '),
        ),
    ]
