# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junto_api', '0006_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Москва', max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
