# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('junto_api', '0007_restaurant_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость на момент заказа, ₽')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итог, ₽')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Cancelled'), (3, 'Done')], default=0, verbose_name='Статус')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, ₽'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(through='junto_api.DishOrder', to='junto_api.Dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', related_query_name='orders', to='junto_api.Restaurant'),
        ),
        migrations.AddField(
            model_name='dishorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junto_api.Dish'),
        ),
        migrations.AddField(
            model_name='dishorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junto_api.Order'),
        ),
    ]
