# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junto_api', '0008_auto_20171006_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итог, ₽'),
        ),
    ]
