# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junto_api', '0011_refreshtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Cancelled')], default=0, verbose_name='Статус'),
        ),
    ]
